
@AppointmentService_HostAddress = http://localhost:5202

@AppointmentService_HostAddress = http://localhost:5056


GET {{AppointmentService_HostAddress}}/weatherforecast/
Accept: application/json

###
